# Practica de Algebra lineal

### *Nombre* RAFAEL LUCENA

In [1]:
import numpy as np

In [2]:
from plotting import plot

In [3]:
import matplotlib.pyplot as plt

<span style="color:blue">Ejercicio 1:  
Usando los procedimientos add y mult_vector_escalar definidos anteriormente, calcular:   
{$\alpha$[1,2]+[3,4] : $\alpha$$\in$$\mathbb{R}$, 0$\leq$$\alpha$$\leq$1, con una precision de dos decimales (para la multiplicación)}</style>

In [4]:
#funcion suma de vectores
def add(v,w):
    return v[0] + w[0],v[1]+w[1]

In [5]:
#multiplicacion de un vector por un escalar
def mult_vector_escalar(alpha,v):
    return [alpha*v[i] for i in range(len(v))]

In [103]:
#calculo analitico
v=[1,2]
w = [3,4]
L = [mult_vector_escalar(i/100,v) for i in range(101)]
r = [add(v2,[3,4]) for v2 in L]

#r
#plot(r)

<span style="color:blue">Ejercicio 2:  
Mortadelo y Filemón usan como clave el siguiente vector:</style>  
> <span style="color:blue">**k**=[0,1,0,0,1,0,1,0,1,0]</style>  

<span style="color:blue">Mortadelo quiere enviarle a Filemón el siguiente mensaje:</style>  
> <span style="color:blue">**p**=[0,0,0,1,1,1,0,1,0,1]</style>  

<span style="color:blue">Mortadelo encripta su mensaje añadiendo k:</style>  
> <span style="color:blue">**c**=**p**+**k**=[0,0,0,1,1,1,0,1,0,1]+[0,1,0,0,1,0,1,0,1,0]=[0,1,0,1,0,1,1,1,1,1]</style>  

<span style="color:blue">Cuando Filemón recibe el mensaje, lo desencripta añadiendo **k** a lo que ha recibido</style>  
> <span style="color:blue">**p**=**c**+**k**=[0,1,0,1,0,1,1,1,1,1]+[0,1,0,0,1,0,1,0,1,0]=[0,0,0,1,1,1,0,1,0,1]</style>    

<span style="color:blue">que es el mensaje original</style>    
  
 <span style="color:blue">¿Cómo lo harías en Python? (Definiendo un procedimiento)</style>  

In [7]:
def encriptador(vector):
    k = [0,1,0,0,1,0,1,0,1,0]
    if len(vector) != 10:
        print('El vector introducido no tiene el tamano adecuado')
    else:    
        return [vector[i]^k[i] for i in range(len(k))] 

In [8]:
mortadelo_encriptacion = encriptador([0,0,0,1,1,1,0,1,0,1])
filemon_desencriptacion = encriptador([0, 1, 0, 1, 0, 1, 1, 1, 1, 1])
filemon_desencriptacion

[0, 0, 0, 1, 1, 1, 0, 1, 0, 1]

<span style="color:blue">Ejercicio 3: coste total o beneficio. </style>

<span style="color:blue">Supongamos que D es el conjunto de algunos ingredientes de la cerveza: </style>
> <span style="color:blue">D={lúpulo, malta, agua, levadura}</style>  

<span style="color:blue">Por otro lado tenemos el vector coste:</style>  
> <span style="color:blue">coste={lúpulo: 2,5€, malta: 1.5€, agua: 0.006€, levadura: 0,45€}</style>  

<span style="color:blue">Por último tenemos el vector cantidad con lo necesario para hacer una cerveza:</style>  
> <span style="color:blue">cantidad={lúpulo: 6u, malta: 14u, agua: 7u, levadura: 11u}</style>  

<span style="color:blue">¿Cuánto cuesta hacer una cerveza?</style> 

In [9]:
coste={'lúpulo': 2.5, 'malta': 1.5, 'agua': 0.006, 'levadura': 0.45}
cantidad={'lúpulo': 6, 'malta': 14, 'agua': 7, 'levadura': 11}

def producto_vectorial(u,v):
    return sum(u[i]*v[i] for i in v)

cerveza = producto_vectorial(coste,cantidad)
cerveza

40.992000000000004

<span style="color:blue"> Ejercicio 4:   
¿Cómo escribirías cada uno de los vectores {[3,0,0],[0,2,0],[0,0,1]} como combinación lineal de {[2,0,1],[1,0,2],[2,2,2]}?
Escribe las combinaciones lineales en Python. Seguramente tenga que definir una nueva suma.</style>

In [10]:
A = np.matrix([[2,1,2],[0,0,2],[1,2,2]])
B = np.matrix([[3],[0],[0]])
X = np.linalg.inv(A).dot(B)
X

matrix([[ 2.],
        [-1.],
        [ 0.]])

In [11]:
A = np.matrix([[2,1,2],[0,0,2],[1,2,2]])
B = np.matrix([[0],[2],[0]])
X = np.linalg.inv(A).dot(B)
X

matrix([[-0.66666667],
        [-0.66666667],
        [ 1.        ]])

In [12]:
A = np.matrix([[2,1,2],[0,0,2],[1,2,2]])
B = np.matrix([[0],[0],[1]])
X = np.linalg.inv(A).dot(B)
X

matrix([[-0.33333333],
        [ 0.66666667],
        [ 0.        ]])

<span style="color:blue"> Ejercicio 5:  
Dadas las matrices $
  A=
  \left[ {\begin{array}{cc}
   2 & -3 \\
   -4 & 6\\
  \end{array} } \right]
$ , $
  B=
  \left[ {\begin{array}{cc}
   8 & 4 \\
   5 & 5\\
  \end{array} } \right]
$
y $
  C=
  \left[ {\begin{array}{cc}
   5 & -2 \\
   3 & 1\\
  \end{array} } \right]
$, queremos verificar que AB=AC pero que B≠C.</style> 

In [13]:
A = np.matrix ([[2,-3],
               [-4,6]])
B = np.matrix ([[8,4],
               [5,5]])
C = np.matrix ([[5,-2],
               [3,1]])

In [16]:
A*B == A*C

matrix([[ True,  True],
        [ True,  True]], dtype=bool)

In [17]:
B == C

matrix([[False, False],
        [False, False]], dtype=bool)

<span style="color:blue"> Ejercicio 6 :  
Dadas la matriz $
  A=
  \left[ {\begin{array}{cc}
   3 & -6 \\
   -1 & 2\\
  \end{array} } \right]
$ , construye una matriz B de 2 × 2 tal que AB sea igual a la matriz cero. Las columnas de B no deben ser iguales entre sí y deben ser distintas de cero.
.</style> 

In [19]:
#ecuaciones
# 3a - 6c = 0
# 3b - 6d = 0
# -a + 2c = 0
# -b + 2d = 0

In [21]:
A = np.matrix([[3,-6],
               [-1,2]])
B = np.matrix([[2,4],
               [1,2]])

In [22]:
C = A * B
C

matrix([[0, 0],
        [0, 0]])

<span style="color:blue"> Ejercicio 7:  
Sarrus para el determinante de orden 3.  
¿Cómo lo haríamos en Python?</style>

In [39]:
A = np.matrix ([[1,-4,2],
               [-2,8,-9],
               [-1,7,0]])

a11 = 1
a12 = -4
a13 = 2
a21 = -2
a22 = 8
a23 = -9
a31 = -1
a32 = 7
a33 = 0

In [40]:
sarrus = (a11*a22*a33)+(a21*a32*a13)+(a12*a23*a31)-((a13*a22*a31)+(a12*a21*a33)+(a11*a23*a32))
sarrus

15

<span style="color:blue"> Ejercicio 8:  
Sabemos que hay un modo directo en Python para calcular los rangos. Calcula el número de soluciones de estos tres sistemas de ecuaciones empleándolo.</style> 

> <span style="color:blue">x<sub>1</sub> − 2x<sub>2</sub> + x<sub>3</sub> = 0 </style>  
> <span style="color:blue">2x<sub>2</sub>−8x<sub>3</sub>= 8  </style>  
> <span style="color:blue">−4x<sub>1</sub> + 5x<sub>2</sub> + 9x<sub>3</sub> =− 9</style>

In [41]:
A = np.matrix ([[1,-2,1,0],
               [0,2,-8,8],
               [-4,5,9,-9]])

print(np.linalg.matrix_rank(A))
B = np.matrix ([[1,-2,1],
               [0,2,-8],
               [-4,5,9]])
print(np.linalg.matrix_rank(B))

3
3


rango A = rango B = incógnitas -> SCD (1 solución)

> <span style="color:blue">x<sub>2</sub> −4x<sub>3</sub> =8  </style>  
> <span style="color:blue">2x<sub>1</sub> −3x<sub>2</sub> + 2x<sub>3</sub> =1  </style>  
> <span style="color:blue">5x<sub>1</sub> −8x<sub>2</sub> + 7x<sub>3</sub> =1</style>

In [104]:
A = np.matrix ([[0,1,-4,8],
               [2,-3,2,1],
               [5,-8,7,1]])
B = np.matrix ([[0,1,-4],
               [2,-3,2],
               [5,-8,7]])
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

3
2


rango A = rango B = incógnitas -> SI (no tiene solución)

> <span style="color:blue">x<sub>1</sub> +x<sub>3</sub> =2  </style>  
> <span style="color:blue">2x<sub>1</sub> +3x<sub>2</sub> + x<sub>3</sub> =3  </style>  
> <span style="color:blue">3x<sub>1</sub> +3x<sub>2</sub> + 2x<sub>3</sub> =5</style>

In [44]:
A = np.matrix ([[1,0,1,2],
               [2,3,1,3],
               [3,3,2,5]])
B = np.matrix ([[1,0,1],
               [2,3,1],
               [3,3,2]])
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

2
2


rango A = rango B < incógnitas -> SCI (multiples soluciones)

<span style="color:blue"> Ejercicio 9:  
Comprobar que r(x,y) para un ángulo $\theta$ es una función lineal.</style> 

Para comprobar que r(x,y) para un angulo $\theta$ es una funcion lineal:
* Para cada vector v en V y cada escalar α en F, f (αv) = αf(v)
* Por cada dos vectores u y v en V, f (u + v) = f (u) + f (v)

si  $
  M =
  \left[ {\begin{array}{cc}
   cos\theta & -sin\theta \\
   sin\theta & cos\theta \\
  \end{array} } \right]
$ es la matriz de traslacion de un angulo $\theta$ 
<span>
y α un escalar:
<br>
<br>
r(x,y)$\cdot$ α = [α $\cdot$ x $\cdot$ cos$\theta$-α$\cdot$x$\cdot$sin$\theta$,α$\cdot$y$\cdot$sin$\theta$+α$\cdot$y$\cdot$cos$\theta$] = α $\cdot$ [x$\cdot$cos$\theta$-x$\cdot$sin$\theta$,y$\cdot$sin$\theta$+y$\cdot$cos$\theta$]= α$\cdot$r(x,y) para un angulo $\theta$
<br>
<br>
Sean u y v dos vectores
<br>
<br>
r(u + v) = r([u1 + v1] , [u2 + v2]) = [(u1+v1)$\cdot$cos$\cdot$$\theta$ - (u1+v1)$\cdot$sin$\theta$,
                                       +(u2+v2)$\cdot$sin$\theta$ + (u2+v2)$\cdot$cos$\theta$] = 
                                    = [u1$\cdot$cos$\cdot$$\theta$+u2$\cdot$$\cdot$cos$\theta$,-u1$\cdot$sin$\theta$-u2$\cdot$sen$\cdot$$\theta$] +
                                      [v1$\cdot$sin$\cdot$$\theta$+v2$\cdot$sin$\theta$,v1$\cdot$cos$\theta$+v2$\cdot$cos$\cdot$$\theta$] = r(u) + r(v)

<span style="color:blue"> Ejercicio 10:  
¿Cuál es la representación coordenada del vector v= [6, 3, 2, 5] en términos de los vectores [2, 2, 2, 3], [1, 0, −1, 0], [0, 1, 0, 1]?</style> 

ecuaciones:
2a + b = 6;
2b + c = 3;
2a - b = 2;
3a + c = 5;

In [45]:
#calculo rangos
A = np.matrix ([[2,1,0,6],
               [2,0,1,3],
               [2,-1,0,2],
               [3,0,1,5]])
B = np.matrix ([[2,1,0],
               [2,0,1],
               [2,-1,0],
               [3,0,1]])
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

3
3


In [46]:
#puedo quitar una ecuacion
# 2a + b = 6
# 2b + c = 3
# 2a - b = 2

In [47]:
A = np.matrix ([[2,1,0,6],
               [2,0,1,3],
               [2,-1,0,2]
               ])
B = np.matrix ([[2,1,0],
               [2,0,1],
               [2,-1,0]
               ])
print(np.linalg.matrix_rank(A))
print(np.linalg.matrix_rank(B))

3
3


In [48]:
A = np.matrix([[2,1,0],[2,0,1],[2,-1,0]])
B = np.matrix([[6],[3],[2]])
X = np.linalg.inv(A).dot(B)
X

matrix([[ 2.],
        [ 2.],
        [-1.]])

[6,3,2,5] = 2* [2,2,2,3] + 2 * [1,0,-1,0] + -1 * [0,1,0,1]

<span style="color:blue"> Ejercicio 11:  
Supongamos que queremos diseñar la red de internet para el otro campus universitario.  
La red debe lograr la misma conectividad que el grafo de entrada.  
Una arista representa un posible cable.  
El peso de la arista es el coste de instalar el cable.  
Nuestro objetivo es minimizar el coste total, usando el algoritmo Grow y el algoritmo Shrink.  </style> 

In [51]:
#algoritmo Grow
#colocamos las aristas en orden creciente
#2,7,9
#se dejan las aristas de 2 y 7
#S= {Penbroke Campus, Athletic Complex},{Penbroke Campus,Bio-med}

In [52]:
#algoritmo Shrink
#quitamos la arista de mayor peso: 9
#S= {Penbroke Campus, Athletic Complex},{Penbroke Campus,Bio-med}    

<span style="color:blue"> Ejercicio 12:  
Sea la matriz $
  M=
  \left[ {\begin{array}{cc}
   1 & 0  & 0 & 5 \\
   0 & 2  & 0 & 7 \\
   0 & 0  & 3 & 9 \\
  \end{array} } \right]
$. Calcular el rango por filas y por columnas usando Python.</style> 

In [53]:
#rango por filas
A = np.matrix ([[1,0,0,5],
               [0,2,0,7],
               [0,0,3,9]
               ])
print(np.linalg.matrix_rank(A))

3


In [54]:
#rango por columnas
B = np.transpose(A)
print(np.linalg.matrix_rank(B))

3


Sale igual porque el rango por filas es igual al rango por columnas

<span style="color:blue"> Ejercicio 13 (opcional):  
Crea un algoritmo que transforme una matriz cualquiera en GF(2) en una matriz escalonada.</style> 

In [24]:
A = np.array([[1,2],[3,4],[5,6]])

In [14]:
A.shape [1]

2

In [19]:
for k in A:
    b = k[0]


In [21]:
A[0]

array([1, 2])

In [25]:
A[2][0]

5

In [20]:
type(b)

numpy.int64

In [29]:
A = np.array([[1,2],[3,4],[5,6]])
nfilas = A.shape[0]
ncolumnas = A.shape[1]
for e in range (0,ncolumnas):
        if (A[0][e]) == '1':
            fila_pivote

1
2


In [ ]:
#utiliza numpy para funcionar
def gaussgf2 (A):
    
    nfilas = A.shape[0]
    ncolumnas = A.shape[1]
    
    for e in range (0,nfilas):
        if A[0][e] == 1:
            
        

In [1]:
import numpy as np

In [6]:
A = np.array([0,1,1,1])

In [115]:
B = np.array([1,1,0,0])

In [118]:
C = A^B

In [119]:
C

array([1, 0, 1, 1])

<span style="color:blue"> Ejercicio 14:  
Modificar lo necesario en los algoritmos para que funcionen y calculen el problema de la casa en llamas.</style>

In [56]:
def proyeccion_paralela(b, a):
    sigma = (b @ a) / (a @ a) if a @ a > 10^-20 else 0
    return sigma * a

In [57]:
def proyeccion_ortogonal(b, a):
    return b - proyeccion_paralela(b, a)

In [71]:
A = np.array([6, 2])
B = np.array([2, 4])

resultado = proyeccion_ortogonal(B, A)
resultado

array([-1.,  3.])

In [73]:
a11 = int(resultado[0])
a11

-1

In [74]:
a12 = int(resultado[1])
a12

3

In [106]:
resultado = np.sqrt((a11**2) + (a12**2))
resultado

3.1622776601683795

la distancia es 2 y la manguera mide 3.5 por lo que la casa se salva

opinión

El contenido del temario me ha parecido adecuado, aunque es cierto que me hubiera gustado ver tensores ya que es un concepto que veremos más adelante y considero que hubiera sido adecuado entender bien el concepto para poder aprovecharlo después.
Respecto a las clases, tal y como comenté en la tutoria y es mi opinión personal todo aquello que ya se ha visto en el prebootcamp debería verse en cada uno de los módulos pero de forma rápida, y de esta forma daría tiempo a ver esos conceptos que considero que podríamos haber visto que pudieran ser de utilidad más adelante.